### ISSUE TITLE
But... ...hardcoded IP address?

### ISSUE THREAD

**Issue by subfission** [ASU-OKED-WEB-DEV/centos7#2]
Check the config.yaml file:  129.219.8.129

You sure you don't want a non-routable IP address: 10.x.x.x or 192.168.x.x?

**Comment by mdyoung3** [comment]
Tried to automate it through Ruby. It didn't seem to like 10.x.x.x. Nor did the 192.168.xx.x number work. You're welcome to give it go though.

**Comment by subfission** [comment]
You tried 192.168.100.1 or 10.0.0.2?

**Comment by mdyoung3** [comment]
Fixed.

**Comment by subfission** [comment]
Approved!
